services:
  # Nginxリバースプロキシ
  nginx:
    image: nginx:latest
    container_name: siteforest_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/front.conf:/etc/nginx/conf.d/front.conf:ro
      - ./nginx/back.conf:/etc/nginx/conf.d/back.conf:ro
      - ./back/public:/var/www/html/public
    depends_on:
      - back
      - front
    restart: always

  # Laravel（PHP-FPM）
  back:
    build:
      context: ./back
      dockerfile: Dockerfile
    container_name: siteforest_back
    volumes:
      - ./back:/var/www/html
    environment:
      - APP_ENV=production
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=SiteForest
      - DB_USERNAME=root
      - DB_PASSWORD=password
    depends_on:
      - db
    restart: always

  # Next.js（フロントエンド）
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: siteforest_front
    volumes:
      - ./front:/front  # ソースコードを同期
      - /front/node_modules  # node_modules をホストと分離
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - back
    restart: always

  # PostgreSQL
  db:
    image: postgres:17.1
    container_name: siteforest_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: SiteForest
    volumes:
      - db:/var/lib/postgresql/data
    restart: always

volumes:
  db:
