FROM php:8.3-fpm

WORKDIR /back

COPY . .

RUN apt-get update && \
    apt-get install -y git unzip libzip-dev libpq-dev && \
    docker-php-ext-install zip pdo pdo_pgsql && \
    docker-php-ext-enable pdo_pgsql

COPY --from=composer:2.7 /usr/bin/composer /usr/bin/composer

RUN composer install --no-dev --optimize-autoloader

EXPOSE 8000
